--if game.PlaceId == 301549746 then return end

if true then
	return
end;

repeat wait() until Utility and Library and Toggle

local function gtwc(text, color)
	return string.format("<font color=\"#%s\">%s</font>", color:ToHex(), text);
end;

local function rc()
	return Color3.fromRGB(math.random(0, 255), math.random(0, 255), math.random(0, 255));
end;

Library:Window({Name = gtwc("Office ", rc()) .. gtwc("Paste", rc())})
    :LeftFooter('Active User: <font color="#00a6ff">dev</font>')
    :Size(UDim2.new(0, 500, 0, 450))
    :Add("Tab", gtwc("Rage", rc()))
        :Add("Section", "Aimbot")
        :Ret()
        :Add("Section", "Anti-Aim")
            :Side("Right")
            :Scale(0.49)
        :Ret()
        :Add("Section", "Hack vs. Hack")
            :Side("Right")
            :Scale(0.49)
            :Size(1)
        :Ret()
    :Ret()
    :Add("Tab", gtwc("Visuals", rc()))
        :Add("Section", "Players")
            :Add("Toggle", "Enabled")
            :Ret()
        :Ret()
    :Ret()
    :Add("Tab", gtwc("Misc", rc()))
        :Add("Section", "Movement")
            :Add("Toggle", "Auto Jump")
                :Flag("Auto Jump")
            :Ret()
            :Add("Toggle", "Speed")
                :Flag("Speed Enabled")
                :Add("Keybind")
                    :Flag("Speed Key")
                    :Key("")
                :Ret()
            :Ret()
            :Add("Dropdown", "Speed Type")
                :Flag("Speed Type")
                :Values({ "Always", "In Air", "On Hop" })
                :Value("Always")
            :Ret()
            :Add("Dropdown", "Speed Mode")
                :Flag("Speed Mode")
                :Values({ "Velocity", "CFrame" })
                :Value("Velocity")
            :Ret()
            :Add("Slider", "Speed Factor")
                :Flag("Speed Factor")
                :Value(60)
                :Min(15)
                :Max(250)
            :Ret()
            :Add("Toggle", "Fly")
                :Flag("Fly Enabled")
                :Add("Keybind")
                    :Flag("Fly Key")
                    :Key("")
                :Ret()
            :Ret()
            :Add("Dropdown", "Fly Mode")
                :Flag("Fly Mode")
                :Values({ "Velocity", "Noclip" })
                :Value("Velocity")
            :Ret()
            :Add("Slider", "Fly Factor")
                :Flag("Fly Factor")
                :Value(60)
                :Min(15)
                :Max(250)
            :Ret()
            :Add("Toggle", "Noclip")
                :Add("Keybind")
                    :Flag("Noclip Key")
                    :Key("")
                :Ret()
            :Ret()
            :Add("Toggle", "Click Teleport")
                :Flag("Click Teleport")
                :Add("Keybind")
                    :Flag("Click Teleport Key")
                    :Key("")
                :Ret()
            :Ret()
        :Ret()
        :Add("Section", "Desync")
            :Side("Right")
            :Scale(0.49)
            :Add("Toggle", "Enabled")
                :Flag("Desync Enabled")
                :Add("Keybind")
                    :Flag("Desync Keybind")
                    :Key("")
                :Ret()
            :Ret()
            :Add("Dropdown", "Position Method")
                :Flag("Desync Position Method")
                :Values({ "Off", "Static", "Random" })
                :Value("Off")
            :Ret()
            :Add("Slider", "X Position")
                :Flag("Desync X Position")
                :Min(-150)
                :Max(150)
                :Value(0)
            :Ret()
            :Add("Slider", "Y Position")
                :Flag("Desync Y Position")
                :Min(-150)
                :Max(150)
                :Value(0)
            :Ret()
            :Add("Slider", "Z Position")
                :Flag("Desync Z Position")
                :Min(-150)
                :Max(150)
                :Value(0)
            :Ret()
            :Add("Dropdown", "Velocity Method")
                :Flag("Desync Velocity Method")
                :Values({ "Off", "Static", "Random", "Fling" })
                :Value("Off")
            :Ret()
            :Add("Slider", "Velocity Multiplier")
                :Flag("Desync Velocity Mult")
                :Min(0)
                :Max(150)
                :Value(0)
            :Ret()
        :Ret()
        :Add("Section", "Extra")
            :Side("Right")
            :Scale(0.49)
            :Size(2)
            :Add("Toggle", "Chat Spam")
                :Flag("Chat Spam Enabled")
            :Ret()
            :Add("Dropdown", "Type")
                :Flag("Chat Spam Type")
                :Values({ "Game Shark", "Toxic", "Troll", "Custom" })
                :Value("Game Shark")
            :Ret()
            :Add("Slider", "Delay")
                :Flag("Chat Spam Delay")
                :Min(0)
                :Max(20)
                :Float(0.1)
                :Value(3)
            :Ret()
            :Add("Toggle", "Repeat")
                :Flag("Chat Spam Repeat")
            :Ret()
            :Add("Toggle", "Emojis")
                :Flag("Chat Spam Emojis")
            :Ret()
            :Add("Toggle", "Symbols")
                :Flag("Chat Spam Symbols")
            :Ret()
        :Ret()
    :Ret()
    :Add("Tab", gtwc("Settings", rc()))
    :Ret()
:Ret()
